#!/usr/bin/env bash
#       __       ____            __    __  __        
#  ___ / /  ___ / / / ___  ___ _/ /__ / /_/ /____    
# (_-</ _ \/ -_) / / / _ \/ _ `/ / -_) __/ __/ -_)   
#/___/_//_/\__/_/_/ / .__/\_,_/_/\__/\__/\__/\__/    
#                  /_/                               
# Script to define and export color palette generated 
# by matugen used by gum terminal script apps 

# Export color palette generated by matugen to gum terminal apps
export MATUGEN_PRIMARY="#99ccfa"
export MATUGEN_ON_PRIMARY="#003351"
export MATUGEN_PRIMARY_CONTAINER="#084b72"
export MATUGEN_ON_PRIMARY_CONTAINER="#cde5ff"
export MATUGEN_SECONDARY="#b8c8da"
export MATUGEN_ON_SECONDARY="#23323f"
export MATUGEN_SURFACE="#101418"
export MATUGEN_ON_SURFACE="#e0e2e8"
export MATUGEN_SURFACE_DIM="#101418"
export MATUGEN_SURFACE_BRIGHT="#36393e"
export MATUGEN_SURFACE_CONTAINER="#1c2024"
export MATUGEN_SURFACE_CONTAINER_HIGH="#272a2e"
export MATUGEN_ON_SURFACE_VARIANT="#c2c7ce"
export MATUGEN_BACKGROUND="#101418"
export MATUGEN_ON_BACKGROUND="#e0e2e8"
export MATUGEN_ERROR="#ffb4ab"
export MATUGEN_ON_ERROR="#690005"