#!/usr/bin/env bash
#       __       ____            __    __  __        
#  ___ / /  ___ / / / ___  ___ _/ /__ / /_/ /____    
# (_-</ _ \/ -_) / / / _ \/ _ `/ / -_) __/ __/ -_)   
#/___/_//_/\__/_/_/ / .__/\_,_/_/\__/\__/\__/\__/    
#                  /_/                               
# Script to define and export color palette generated 
# by matugen used by gum terminal script apps 

# Export color palette generated by matugen to gum terminal apps
export MATUGEN_PRIMARY="#a6d394"
export MATUGEN_ON_PRIMARY="#13380a"
export MATUGEN_PRIMARY_CONTAINER="#2a4f1f"
export MATUGEN_ON_PRIMARY_CONTAINER="#c2efae"
export MATUGEN_SECONDARY="#bbcbb1"
export MATUGEN_ON_SECONDARY="#273421"
export MATUGEN_SURFACE="#11140f"
export MATUGEN_ON_SURFACE="#e1e4da"
export MATUGEN_SURFACE_DIM="#11140f"
export MATUGEN_SURFACE_BRIGHT="#373a34"
export MATUGEN_SURFACE_CONTAINER="#1d211b"
export MATUGEN_SURFACE_CONTAINER_HIGH="#272b25"
export MATUGEN_ON_SURFACE_VARIANT="#c3c8bc"
export MATUGEN_BACKGROUND="#11140f"
export MATUGEN_ON_BACKGROUND="#e1e4da"
export MATUGEN_ERROR="#ffb4ab"
export MATUGEN_ON_ERROR="#690005"