[General]
ColorScheme=Matugen
Name=Matugen

[Appearance]
color_scheme=Matugen

[Colors:Button]
BackgroundAlternate=#1f1b13
BackgroundNormal=#2e2921
DecorationFocus=#e6c36c
DecorationHover=#e6c36c
ForegroundActive=#e6c36c
ForegroundInactive=#cfc5b4
ForegroundLink=#d6c5a0
ForegroundNegative=#ffb4ab
ForegroundNeutral=#aecfac
ForegroundNormal=#eae1d4
ForegroundPositive=#caebc7
ForegroundVisited=#f3e1bb

[Colors:Complementary]
BackgroundAlternate=#1f1b13
BackgroundNormal=#16130b
DecorationFocus=#e6c36c
DecorationHover=#e6c36c
ForegroundActive=#e6c36c
ForegroundInactive=#cfc5b4
ForegroundLink=#d6c5a0
ForegroundNegative=#ffb4ab
ForegroundNeutral=#aecfac
ForegroundNormal=#ffdf95
ForegroundPositive=#caebc7
ForegroundVisited=#f3e1bb

[Colors:Header]
BackgroundAlternate=#16130b
BackgroundNormal=#231f17
DecorationFocus=#e6c36c
DecorationHover=#e6c36c
ForegroundActive=#e6c36c
ForegroundInactive=#cfc5b4
ForegroundLink=#d6c5a0
ForegroundNegative=#ffb4ab
ForegroundNeutral=#aecfac
ForegroundNormal=#eae1d4
ForegroundPositive=#caebc7
ForegroundVisited=#f3e1bb

[Colors:Header][Inactive]
BackgroundAlternate=#231f17
BackgroundNormal=#16130b
DecorationFocus=#e6c36c
DecorationHover=#e6c36c
ForegroundActive=#e6c36c
ForegroundInactive=#cfc5b4
ForegroundLink=#d6c5a0
ForegroundNegative=#ffb4ab
ForegroundNeutral=#aecfac
ForegroundNormal=#eae1d4
ForegroundPositive=#caebc7
ForegroundVisited=#f3e1bb

[Colors:Selection]
BackgroundAlternate=#1f1b13
BackgroundNormal=#e6c36c
DecorationFocus=#e6c36c
DecorationHover=#e6c36c
ForegroundActive=#3e2e00
ForegroundInactive=#cfc5b4
ForegroundLink=#f3e1bb
ForegroundNegative=#93000a
ForegroundNeutral=#aecfac
ForegroundNormal=#3e2e00
ForegroundPositive=#314d32
ForegroundVisited=#f3e1bb

[Colors:Tooltip]
BackgroundAlternate=#16130b
BackgroundNormal=#231f17
DecorationFocus=#e6c36c
DecorationHover=#e6c36c
ForegroundActive=#e6c36c
ForegroundInactive=#cfc5b4
ForegroundLink=#d6c5a0
ForegroundNegative=#ffb4ab
ForegroundNeutral=#aecfac
ForegroundNormal=#eae1d4
ForegroundPositive=#caebc7
ForegroundVisited=#f3e1bb

[Colors:View]
BackgroundAlternate=#231f17
BackgroundNormal=#16130b
DecorationFocus=#e6c36c
DecorationHover=#51452a
ForegroundActive=#e6c36c
ForegroundInactive=#cfc5b4
ForegroundLink=#d6c5a0
ForegroundNegative=#ffb4ab
ForegroundNeutral=#aecfac
ForegroundNormal=#eae1d4
ForegroundPositive=#caebc7
ForegroundVisited=#f3e1bb

[Colors:Window]
BackgroundAlternate=#594400
BackgroundNormal=#231f17
DecorationFocus=#e6c36c
DecorationHover=#e6c36c
ForegroundActive=#e6c36c
ForegroundInactive=#cfc5b4
ForegroundLink=#d6c5a0
ForegroundNegative=#ffb4ab
ForegroundNeutral=#aecfac
ForegroundNormal=#eae1d4
ForegroundPositive=#caebc7
ForegroundVisited=#f3e1bb

[ColorEffects:Disabled]
Color=#16130b
ColorAmount=0
ColorEffect=0
ContrastAmount=0.65
ContrastEffect=1
IntensityAmount=0.1
IntensityEffect=2

[ColorEffects:Inactive]
ChangeSelectionColor=true
Color=#4d4639
ColorAmount=0.025
ColorEffect=2
ContrastAmount=0.1
ContrastEffect=2
Enable=false
IntensityAmount=0
IntensityEffect=0

[KDE]
contrast=0

[WM]
activeBackground=#594400
activeBlend=#ffdf95
activeForeground=#ffdf95
inactiveBackground=#16130b
inactiveBlend=#cfc5b4
inactiveForeground=#cfc5b4