# _  ___ _   _         
#| |/ (_) |_| |_ _   _ 
#| ' /| | __| __| | | |
#| . \| | |_| |_| |_| |
#|_|\_\_|\__|\__|\__, |
#                |___/ 
# Configuration
shell /usr/bin/fish

font_family                 JetBrainsMono Nerd Font
font_size                   12
bold_font                   auto
italic_font                 auto
bold_italic_font            auto
remember_window_size        no
initial_window_width        950
initial_window_height       500
cursor_blink_interval       0.5
cursor_stop_blinking_after  1
scrollback_lines            2000
wheel_scroll_min_lines      1
enable_audio_bell           no
window_padding_width        10
hide_window_decorations     yes
background_opacity          0.2
dynamic_background_opacity  yes
confirm_os_window_close     0
selection_foreground        none
selection_background        none

foreground           #cdd6f4
selection_foreground #11111b
selection_background #89b4fa
color0               #1e1e2e
color8               #45475a
color1               #f38ba8
color9               #f38ba8
color2               #a6e3a1
color10              #a6e3a1
color3               #f9e2af
color11              #f9e2af
color4               #89b4fa
color12              #89b4fa
color5               #f5c2e7
color13              #f5c2e7
color6               #94e2d5
color14              #94e2d5
color7               #bac2de
color15              #a6adc8
