shell fish
title_title_template foot

font_family JetBrains Mono Nerd Font
font_size 12.0

disable_ligatures never
adjust_line_height 0
adjust_column_width 0

window_padding_width 25

background_opacity 0.78

cursor_shape beam
cursor_beam_thickness 1.5

scrollback_lines 10000

map page_up scroll_page_up
map page_down scroll_page_down

map ctrl+shift+f show_scrollback
