#!/usr/bin/env bash
#       __       ____            __    __  __        
#  ___ / /  ___ / / / ___  ___ _/ /__ / /_/ /____    
# (_-</ _ \/ -_) / / / _ \/ _ `/ / -_) __/ __/ -_)   
#/___/_//_/\__/_/_/ / .__/\_,_/_/\__/\__/\__/\__/    
#                  /_/                               
# Script to define and export color palette generated 
# by matugen used by gum terminal script apps 

# Export color palette generated by matugen to gum terminal apps
export MATUGEN_PRIMARY="{{colors.primary.default.hex}}"
export MATUGEN_ON_PRIMARY="{{colors.on_primary.default.hex}}"
export MATUGEN_PRIMARY_CONTAINER="{{colors.primary_container.default.hex}}"
export MATUGEN_ON_PRIMARY_CONTAINER="{{colors.on_primary_container.default.hex}}"
export MATUGEN_SECONDARY="{{colors.secondary.default.hex}}"
export MATUGEN_ON_SECONDARY="{{colors.on_secondary.default.hex}}"
export MATUGEN_SURFACE="{{colors.surface.default.hex}}"
export MATUGEN_ON_SURFACE="{{colors.on_surface.default.hex}}"
export MATUGEN_SURFACE_DIM="{{colors.surface_dim.default.hex}}"
export MATUGEN_SURFACE_BRIGHT="{{colors.surface_bright.default.hex}}"
export MATUGEN_SURFACE_CONTAINER="{{colors.surface_container.default.hex}}"
export MATUGEN_SURFACE_CONTAINER_HIGH="{{colors.surface_container_high.default.hex}}"
export MATUGEN_ON_SURFACE_VARIANT="{{colors.on_surface_variant.default.hex}}"
export MATUGEN_BACKGROUND="{{colors.background.default.hex}}"
export MATUGEN_ON_BACKGROUND="{{colors.on_background.default.hex}}"
export MATUGEN_ERROR="{{colors.error.default.hex}}"
export MATUGEN_ON_ERROR="{{colors.on_error.default.hex}}"